#import "CGIHTTPStatus.h"

NSDictionary * CGIHTTPStatus(void) { return @{@"449": @"Retry With", 
@"414": @"Request-URI Too Long", 
@"302": @"Found", 
@"407": @"Proxy Authentication Required", 
@"499": @"Client Closed Request", 
@"415": @"Unsupported Media Type", 
@"226": @"IM Used", 
@"422": @"Unprocessable Entity", 
@"303": @"See Other", 
@"408": @"Request Timeout", 
@"409": @"Conflict", 
@"304": @"Not Modified", 
@"416": @"Requested Range Not Satisfiable", 
@"423": @"Locked", 
@"500": @"Internal Server Error", 
@"417": @"Expectation Failed", 
@"305": @"Use Proxy", 
@"200": @"OK", 
@"424": @"Method Failure", 
@"431": @"Request Header Fields Too Large", 
@"501": @"Not Implemented", 
@"418": @"I'm a teapot", 
@"306": @"Switch Proxy", 
@"201": @"Created", 
@"425": @"Unordered Collection", 
@"502": @"Bad Gateway", 
@"426": @"Upgrade Required", 
@"307": @"Temporary Redirect", 
@"202": @"Accepted", 
@"503": @"Service Unavailable", 
@"510": @"Not Extended", 
@"504": @"Gateway Timeout", 
@"308": @"Permanent Redirect", 
@"203": @"Non-Authoritative Information", 
@"511": @"Network Authentication Required", 
@"428": @"Precondition Required", 
@"400": @"Bad Request", 
@"204": @"No Content", 
@"505": @"HTTP Version Not Supported", 
@"429": @"Too Many Requests", 
@"401": @"Unauthorized", 
@"205": @"Reset Content", 
@"100": @"Continue", 
@"450": @"Blocked by Windows Parental Controls", 
@"506": @"Variant Also Negotiates", 
@"598": @"Network read timeout error", 
@"444": @"No Response", 
@"402": @"Payment Required", 
@"206": @"Partial Content", 
@"101": @"Switching Protocols", 
@"451": @"Redirect", 
@"507": @"Insufficient Storage", 
@"599": @"Network connect timeout error", 
@"494": @"Request Header Too Large", 
@"508": @"Loop Detected", 
@"403": @"Forbidden", 
@"207": @"Multi-Status", 
@"410": @"Gone", 
@"102": @"Processing", 
@"495": @"Cert Error", 
@"509": @"Bandwidth Limit Exceeded", 
@"404": @"Not Found", 
@"208": @"Already Reported", 
@"411": @"Length Required", 
@"496": @"No Cert", 
@"405": @"Method Not Allowed", 
@"300": @"Multiple Choices", 
@"412": @"Precondition Failed", 
@"497": @"HTTP to HTTPS", 
@"420": @"Enhance Your Calm", 
@"301": @"Moved Permanently", 
@"406": @"Not Acceptable", 
@"413": @"Request Entity Too Large"}; }
